### ISSUE TITLE
Adding `epithet-rename-buffer` to `help-mode-hook` interferes with `vc-annotate`

### ISSUE THREAD

**Issue by okamsn** [oantolin/epithet#1]
Just so you know, adding it to the help hook breaks `vc-annotate`, in that it won't be able to find the annotation buffer.

I don't know why the annotation buffer is triggering the `help-mode-hook`.

**Comment by oantolin** [comment]
Oh, sorry for not seeing this before! I used to think that GitHub would notify me of new issues.

`vc-annotate` uses `with-output-to-temp-buffer`, which makes a new help mode buffer. You are supposed to change the major mode in the body of `with-output-to-temp-buffer` if you want to, and `vc-annotate` changes it `vc-annotate-mode`. By then epithet already screwed the name up. I'll check the name before I go around suggesting a new one.
