### ISSUE TITLE
occur-rename-buffer and epithet-for-occur using nil instead of descriptive names

### ISSUE THREAD

**Issue by Aeyk** [oantolin/epithet#10]
using occur results in the occur buffer-name becoming \*Occur: nil in \*

i havent done a deep dive in the code but it seems like it's trying to
name the buffer without being it the focused buffer

running M-: (epithet-suggestion) in an occur buffer has what i
want i.e "**Occur: \* in epithet.el**"

running M-: (epithet-rename-buffer) in an occur buffer also has what I
want  i.e "**Occur: \* in epithet.el**"

running M-: (epithet-for-occur) in an occur buffer also has what I
want  i.e "**Occur: \* in epithet.el**"

running M-: (epithet-for-occur) in an source buffer that I'm searching
with occur shows nil

M-: (emacs-version) "GNU Emacs 29.0.91 (build 1, x86<sub>64</sub>-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0")

reproduce.el

    (require 'package)
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    
    (package-initialize)
    (unless package-archive-contents
      (package-refresh-contents))	
    
    (use-package emacs ;; quelpa
      :config
      (unless (package-installed-p 'quelpa)
    	(with-temp-buffer
    	  (url-insert-file-contents "https://raw.githubusercontent.com/quelpa/quelpa/master/quelpa.el")
    	  (eval-buffer)
    	  (quelpa-self-upgrade)))
      (quelpa
       '(quelpa-use-package
    	 :fetcher git
    	 :url "https://github.com/quelpa/quelpa-use-package.git"))
      (setq quelpa-upgrade-interval 7)	
      (require 'use-package)
      (require 'quelpa-use-package)
      (add-to-list 'auto-mode-alist '("\\.txt\\'" . org-mode))
      (recentf-mode 1))
    
    
    (use-package epithet
      :quelpa ((epithet :fetcher github :repo "oantolin/epithet"))
      :config
      (add-hook 'occur-mode-hook #'epithet-rename-buffer))

in shell

    emacs -Q --load ./reproduce.el

**Comment by oantolin** [comment]
You mention `occur-rename-buffer` in the issue title, does the problem also happen with that function?

**Comment by oantolin** [comment]
Oh, I just noticed you are adding `epithet-rename-buffer` to `occur-mode-hook`! You are supposed to add it to `occur-hook` instead.

**Comment by oantolin** [comment]
Oh, the documentation says to add it to `occur-mode-hook`. I'm sorry about that, I'll fix it right away.

**Comment by oantolin** [comment]
Done, fixed the README.

By the way, the docstring for `occur-rename-buffer` also says to add it to `occur-hook`, not `occur-mode-hook`.
