### ISSUE TITLE
*Help* buffer still exists after rename

### ISSUE THREAD

**Issue by DamienCassou** [oantolin/epithet#7]
In a normal Emacs session, renaming a buffer means the old name doesn't refer to a buffer anymore:

```session
$ emacs --batch -Q --eval "(describe-function #'describe-function)" --eval "(with-current-buffer \"*Help*\" (rename-buffer \"*Help: describe-function*\" t))" --eval "(prin1 (get-buffer \"*Help*\"))"
nil
```

This seems ok to me: renaming `*Help*` to `*Help: describe-function*` makes `*Help*` non existing.

But things doesn't work this way with epithet:

```
$ emacs --batch -Q -L ~/.emacs.d/lib/epithet/ -l epithet --eval "(add-hook 'help-mode-hook #'epithet-rename-buffer)" --eval "(describe-function #'describe-function)" --eval "(prin1 (get-buffer \"*Help*\"))"
#<buffer *Help*>
```

As you can see, the `*Help*` buffer still exists after the "rename". 

The problem doesn't seem to come from `epithet-rename-buffer` but from the usage of `help-mode-hook` to rename a buffer:

```
$ emacs --batch -Q --eval "(add-hook 'help-mode-hook (lambda () (rename-buffer \"*foo*\")))" --eval "(describe-function #'describe-function)" --eval "(prin1 (get-buffer \"*Help*\"))"
#<buffer *Help*>
```

As you can see, using the hook to rename a help buffer doesn't work as the old name still refers to a buffer.

**Comment by DamienCassou** [comment]
I reported [the issue to Emacs maintainers](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=57816).

**Comment by DamienCassou** [comment]
Emacs maintainers answered that the bug is fixed in Emacs 29. Feel free to close the issue.

**Comment by oantolin** [comment]
OK, thanks, I will close.
